import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedMahasiswas() {
  const mahasiswaData = [
    {
      nim: "20210001",
      nama: "Ahmad Fauzi",
      angkatan: "2021",
      jurusan: "Teknik Informatika",
      email: "ahmad.fauzi@example.com",
      isActive: true,
      fotoUrl: "",
      fakultas: "Fakultas Teknik",
      konsentrasi: "Sistem Informasi",
      agama: "Islam",
      alamat: "Jl. Merpati No.10",
      telp: "081234567890",
      asalSekolah: "SMA Negeri 1 Jakarta",
      jalurMasuk: "SNMPTN",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-15"),
      dosenWaliId: 1,
    },
    {
      nim: "20210002",
      nama: "Siti Nurhaliza",
      angkatan: "2021",
      jurusan: "Teknik Elektro",
      email: "siti.nurhaliza@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Islam",
      alamat: "Jl. Melati No.5",
      telp: "081234567891",
      asalSekolah: "SMA Negeri 2 Bandung",
      jalurMasuk: "SBMPTN",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-20"),
      dosenWaliId: 2,
    },
    // Tambahkan 8 data mahasiswa lainnya dengan pola serupa
    {
      nim: "20210003",
      nama: "Budi Santoso",
      angkatan: "2021",
      jurusan: "Teknik Mesin",
      email: "budi.santoso@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Kristen",
      alamat: "Jl. Kenanga No.8",
      telp: "081234567892",
      asalSekolah: "SMA Negeri 3 Surabaya",
      jalurMasuk: "SNMPTN",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-17"),
      dosenWaliId: 3,
    },
    {
      nim: "20210004",
      nama: "Dewi Lestari",
      angkatan: "2021",
      jurusan: "Teknik Sipil",
      email: "dewi.lestari@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Islam",
      alamat: "Jl. Anggrek No.12",
      telp: "081234567893",
      asalSekolah: "SMA Negeri 4 Yogyakarta",
      jalurMasuk: "Mandiri",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-18"),
      dosenWaliId: 1,
    },
    {
      nim: "20210005",
      nama: "Eko Prasetyo",
      angkatan: "2021",
      jurusan: "Teknik Kimia",
      email: "eko.prasetyo@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Islam",
      alamat: "Jl. Dahlia No.20",
      telp: "081234567894",
      asalSekolah: "SMA Negeri 5 Semarang",
      jalurMasuk: "SBMPTN",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-22"),
      dosenWaliId: 2,
    },
    {
      nim: "20210006",
      nama: "Fajar Nugroho",
      angkatan: "2021",
      jurusan: "Teknik Informatika",
      email: "fajar.nugroho@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Islam",
      alamat: "Jl. Kenari No.15",
      telp: "081234567895",
      asalSekolah: "SMA Negeri 6 Jakarta",
      jalurMasuk: "SNMPTN",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-21"),
      dosenWaliId: 3,
    },
    {
      nim: "20210007",
      nama: "Gita Lestari",
      angkatan: "2021",
      jurusan: "Teknik Elektro",
      email: "gita.lestari@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Kristen",
      alamat: "Jl. Mawar No.10",
      telp: "081234567896",
      asalSekolah: "SMA Negeri 7 Bandung",
      jalurMasuk: "Mandiri",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-19"),
      dosenWaliId: 1,
    },
    {
      nim: "20210008",
      nama: "Hadi Susanto",
      angkatan: "2021",
      jurusan: "Teknik Mesin",
      email: "hadi.susanto@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Islam",
      alamat: "Jl. Melati No.9",
      telp: "081234567897",
      asalSekolah: "SMA Negeri 8 Surabaya",
      jalurMasuk: "SNMPTN",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-20"),
      dosenWaliId: 2,
    },
    {
      nim: "20210009",
      nama: "Indah Permata",
      angkatan: "2021",
      jurusan: "Teknik Sipil",
      email: "indah.permata@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Islam",
      alamat: "Jl. Cemara No.11",
      telp: "081234567898",
      asalSekolah: "SMA Negeri 9 Yogyakarta",
      jalurMasuk: "SBMPTN",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-22"),
      dosenWaliId: 3,
    },
    {
      nim: "20210010",
      nama: "Joko Widodo",
      angkatan: "2021",
      jurusan: "Teknik Kimia",
      email: "joko.widodo@example.com",
      isActive: true,
      fakultas: "Fakultas Teknik",
      agama: "Islam",
      alamat: "Jl. Kenanga No.14",
      telp: "081234567899",
      asalSekolah: "SMA Negeri 10 Medan",
      jalurMasuk: "Mandiri",
      tahunMasuk: "2021",
      tanggalMasuk: new Date("2021-08-23"),
      dosenWaliId: 1,
    },
  ];

  for (const mhs of mahasiswaData) {
    await prisma.dataMahasiswa.upsert({
      where: { nim: mhs.nim },
      update: {},
      create: mhs,
    });
  }

  console.log("Seeder DataMahasiswa selesai!");
}

async function main() {
  try {
    await seedMahasiswas();
  } catch (error) {
    console.error(error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
